import {
  faBell,
  faComments,
  faHouse,
  faImage,
  faTableColumns,
  faUpload,
} from "@fortawesome/free-solid-svg-icons";

export const leftSidebarLinks = [
  {
    icon: faHouse,
    route: "/",
    label: "Home",
  },
  {
    icon: faTableColumns,
    route: "/dashboard",
    label: "Dashboard",
  },
  {
    icon: faImage,
    route: "/posts",
    label: "My Posts",
  },
  {
    icon: faUpload,
    route: "/create-post",
    label: "Create post",
  },

  {
    icon: faComments,
    route: "/chatting",
    label: "Messages",
  },
  {
    icon: faBell,
    route: "/notifications",
    label: "Notifications",
  },
];


export const countries = [
  "Algeria",
  "Bahrain",
  "Comoros",
  "Djibouti",
  "Egypt",
  "Iraq",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Libya",
  "Mauritania",
  "Morocco",
  "Oman",
  "Palestine",
  "Qatar",
  "Saudi Arabia",
  "Somalia",
  "Sudan",
  "Syria",
  "Tunisia",
  "United Arab Emirates",
  "Yemen",
];

export const cities = {
  Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Batna"],
  Bahrain: ["Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town"],
  Comoros: ["Moroni", "Moutsamoudou", "Fomboni", "Domoni", "Tsimbeo"],
  Djibouti: ["Djibouti City", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said"],
  Iraq: ["Baghdad", "Basra", "Sulaymaniyah", "Erbil", "Najaf"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Russeifa", "Al-Salt"],
  Kuwait: [
    "Kuwait City",
    "Al Ahmadi",
    "Hawalli",
    "As Salimiyah",
    "Sabah as Salim",
  ],
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  Libya: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Zawiya"],
  Mauritania: ["Nouakchott", "Nouadhibou", "Kiffa", "Zouérat", "Atar"],
  Morocco: ["Casablanca", "Rabat", "Fes", "Marrakesh", "Tangier"],
  Oman: ["Muscat", "Seeb", "Salalah", "Bawshar", "Suhar"],
  Palestine: [
    "Jerusalem",
    "Gaza",
    "Hebron",
    "Nablus",
    "Rafah",
    "Ya'bad",
    "Tulkarm",
    "Tubas",
    "Surif",
    "Sa'ir",
    "Ramallah",
    "Qalqilya",
    "Qabatiya",
    "Khan Yunis",
    "Jericho (Ariha)",
    "Jenin",
    "Jabalia",
    "Idhna",
    "Hebron (al-Khalil)",
    "Halhul",
    "Gaza City (Ghazzah)",
    "Dura",
    "Deir al-Balah",
    "Bethlehem (Beit Lahm)",
    "Beitunia",
    "Beit Ummar",
    "Beit Sahour",
    "Beit Lahia",
    "Beit Jala",
    "Beit Hanoun",
    "Bani Suheila",
    "Bani Na'im",
    "az-Zawayda",
    "as-Samu",
    "al-Yamun",
    "al-Bireh",
    "ad-Dhahiriya",
    "Abu Dis",
  ],
  Qatar: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  Somalia: ["Mogadishu", "Hargeisa", "Bosaso", "Kismaayo", "Mereeg"],
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid"],
  Syria: ["Damascus", "Aleppo", "Homs", "Hama", "Latakia"],
  Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  Yemen: ["Sanaa", "Aden", "Taiz", "Al Hudaydah", "Ibb"],
};
